### ISSUE TITLE
Few questions about this library

### ISSUE THREAD

**Issue by Dukobpa3** [bromix/kodion#59]
1. May I use it in my addon? :)
2. Is it have any license?
3. Why don't you publish it as 3-d party module to kodi repos?
4. Any docs, tips, etc. about using it? :)

**Comment by bromix** [comment]
1. Better not - at the moment the devs KODI  allow to include the framework for my addon.
2. No license
3. Won't work (see swiftxbmc) if something changes all addons are affected and not always for good. Bad idea in my experience. For example some addons are running with version 1.2.0 and wouldn't be compatible with 1.4.0
4. no, because of no publication

**Comment by Dukobpa3** [comment]
Ok. Thanks :)
